### ISSUE TITLE
[Bug] Option Documentation in README Does Not Mirror Application Help

### ISSUE THREAD

**Issue by kevinmatthes** [wert007/commit-analyzer#31]
Due to #27, there should be an update to the respective section of the README.

**Comment by kevinmatthes** [comment]
Hello, @wert007!

It has been a long time since I contributed the last time but I think I have found a convenient solution to keep the documentation and the README up-to-date.

I wrote an application which mirrors the description of a Rust project from the library crate to the README.  As it is already published to crates.io, I could configure a GitHub Action workflow to grab the README from the source code whenever the crate root is edited.  That way, the SPOT principle is fulfilled in an efficient manner.  The contents of the README just need to be moved to src/lib.rs initially.  Changes to the calling interface can be documented in the crate's description directly when editing the source file anyway such that the GitHub Action workflow will mirror the changes to README in a separate commit afterwards.

Would this be an appropriate solution for you?

**Comment by wert007** [comment]
Hey!

I've also stopped working on this project, since I'm not really in need of it.

I do not think, that this is published to crates.io. Your proposal sounds interesting, but again I'm not really interested in this project at this time. So feel free to do what you would like to do, but do not expect anything from myself.. 😅
